[KMA]
API_KEY = "tY8VLwuj4xgpv5%2FRvL9hClEoJJMLlK5qtBj%2FpaNY%2FAfX2nFuXUg3utCLLK%2FBdE6Dh3td1JQrqGUv3Ml4Xw7GwA%3D%3D"

[ASOS]
API_KEY = "tY8VLwuj4xgpv5%2FRvL9hClEoJJMLlK5qtBj%2FpaNY%2FAfX2nFuXUg3utCLLK%2FBdE6Dh3td1JQrqGUv3Ml4Xw7GwA%3D%3D"

[GITHUB]
USERNAME = "dalsoup"
REPO = "0725"
TOKEN = "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"
BRANCH = "main"
