[KMA]
API_KEY = "tY8VLwuj4xgpv5%2FRvL9hClEoJJMLlK5qtBj%2FpaNY%2FAfX2nFuXUg3utCLLK%2FBdE6Dh3td1JQrqGUv3Ml4Xw7GwA%3D%3D"

[ASOS]
API_KEY = "tY8VLwuj4xgpv5%2FRvL9hClEoJJMLlK5qtBj%2FpaNY%2FAfX2nFuXUg3utCLLK%2FBdE6Dh3td1JQrqGUv3Ml4Xw7GwA%3D%3D"

[GITHUB]
USERNAME = "dalsoup"
REPO = "0725"
TOKEN = "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"
BRANCH = "main"
